# Site settings
title: Home of Guangyu Zhao  # homepage title
description: Once you have tasted flight, you will forever walk the earth with your eyes turned skyward, for there you have been, and there you will always long to return.  # homepage description
baseurl: "" 
url: "https://guangyu-zhao.github.io" 

# GitHub User settings
username: guangyu-zhao
github_username: guangyu-zhao
user_description: An undergraduate from THU
user_title: Undergraduate
email: zgy20010917@gmail.com

# Blog Author settings
author:
  name:           guangyu-zhao
  picture:        
  email:          zhaogy20@mails.tsinghua.edu.cn, jellerode@outlook.com, zgy20010917@gmail.com
  description:    An undergraduate from THU
  twitter:
  facebook:
  github:         https://github.com/guangyu-zhao
  linkedin:
  # If you're forking this site, make sure you delete this entry!
  #clustrmap:      MlqUzlcZFdHetSQuxml5oHyt9RwVjZrsGbvyaRpMwgU
  # If you're forking this site, make sure you delete this entry!


# markdown
markdown: kramdown

future: true
  
kramdown:
 footnote_nr: 1
 entity_output: as_char
 # Jekyll 3 and GitHub Pages now only support rouge for syntax highlighting
 syntax_highlighter: rouge
 syntax_highlighter_opts:
  # Use existing pygments syntax highlighting css
  css_class: 'highlight'
 span:
  line_numbers: false
 block:
  line_numbers: true
  start_line: 1
 
highlighter: rouge
    
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  
permalink: /:year/:title/

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      toc: true
      mathjax: true
      mermaid: false
      highlight: false
      numbering: true
      status: Completed
      protected: false
      commentable: true
      rss: true
      numbering: true

exclude:
 - LICENSE.md
 - README.md
 - "*.cdf"
 - "*.tex"
 - "*.aux"
 - "*.log"
 - "*.out"
 - "*.gz"
 - "*.toc"
 - "*.bib"
 - "*.nb"
 - "*.bk"
 - "*.draft.md"
 - "*.source.*"